name: Load Test Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  k6-load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run Load Test in K6 Cloud
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: |
          k6 cloud tests/load/k6-colibri.js \
            -e BASE_URL=https://colibri-backend-od5b.onrender.com \
            -e USER=test@colibri.com \
            -e PASS=1234
