name: k6 Load Test

on:
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run k6 load test
      uses: grafana/run-k6-action@v0.2.0
      with:
        # Aquí puedes especificar la URL a probar
        script: test/to/load-test.js
        cloud: true # Para subir los resultados a Grafana Cloud
      env:
        K6_CLOUD_TOKEN: ${{ secrets.GRAFANA_CLOUD_K6_TOKEN_DIEGO }} # Token de Grafana Cloud
